# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 18:00
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161007_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='coords',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
